-- Seed: distritos de Paraguay (municipios) + capital Asunción.
-- Referencia: listado de distritos (Statoids, 268 nombres únicos).
-- Idempotente: ON CONFLICT (nombre) DO NOTHING.

BEGIN;

DO $migration$
BEGIN
  IF NOT EXISTS (SELECT 1 FROM pg_namespace WHERE nspname = 'lilian_inmobiliaria') THEN
    RAISE NOTICE 'Schema lilian_inmobiliaria no existe; omitido.';
    RETURN;
  END IF;
  IF to_regclass('lilian_inmobiliaria.ciudades') IS NULL THEN
    RAISE NOTICE 'Tabla ciudades no existe; omitido.';
    RETURN;
  END IF;

  INSERT INTO lilian_inmobiliaria.ciudades (nombre)
  VALUES
  ('25 de Diciembre'),
  ('3 de Febrero'),
  ('3 de Mayo'),
  ('Abaí'),
  ('Acahay'),
  ('Alberdi'),
  ('Alto Verá'),
  ('Altos'),
  ('Antequera'),
  ('Areguá'),
  ('Arroyito'),
  ('Arroyos y Esteros'),
  ('Asunción'),
  ('Atyrá'),
  ('Ayolas'),
  ('Azote''y'),
  ('Bahía Negra'),
  ('Belén'),
  ('Bella Vista'),
  ('Bella Vista Norte'),
  ('Benjamín Aceval'),
  ('Boquerón'),
  ('Borja'),
  ('Buena Vista'),
  ('Caacupé'),
  ('Caaguazú'),
  ('Caapucú'),
  ('Caazapá'),
  ('Cambyretá'),
  ('Campo Aceval'),
  ('Capiatá'),
  ('Capiibary'),
  ('Capitán Bado'),
  ('Capitán Mauricio José Troche'),
  ('Capitán Meza'),
  ('Capitán Miranda'),
  ('Caraguatay'),
  ('Carapeguá'),
  ('Carayaó'),
  ('Carlos Antonio López'),
  ('Carmelo Peralta'),
  ('Carmen del Paraná'),
  ('Cerrito'),
  ('Cerro Corá'),
  ('Choré'),
  ('Ciudad del Este'),
  ('Concepción'),
  ('Coronel Bogado'),
  ('Coronel Martínez'),
  ('Coronel Oviedo'),
  ('Corpus Christi'),
  ('Curuguaty'),
  ('Desmochados'),
  ('Domingo Martínez de Irala'),
  ('Dr. Bottrell'),
  ('Dr. Cecilio Báez'),
  ('Dr. J. Eulogio Estigarribia'),
  ('Dr. Juan León Mallorquín'),
  ('Dr. Juan Manuel Frutos'),
  ('Dr. Moisés S. Bertoni'),
  ('Dr. Raúl Peña'),
  ('Edelira'),
  ('Emboscada'),
  ('Encarnación'),
  ('Escobar'),
  ('Eusebio Ayala'),
  ('Félix Pérez Cardozo'),
  ('Fernando de la Mora'),
  ('Filadelfia'),
  ('Fram'),
  ('Francisco Caballero Alvarez'),
  ('Fuerte Olimpo'),
  ('General Artigas'),
  ('General Bernardino Caballero'),
  ('General Delgado'),
  ('General Elizardo Aquino'),
  ('General Francisco Isidoro Resquín'),
  ('General Higinio Morinigo'),
  ('General José Eduvigis Díaz'),
  ('General José María Bruguez'),
  ('Gral. Eugenio A. Garay'),
  ('Guajayvi'),
  ('Guarambaré'),
  ('Guazú-Cuá'),
  ('Hernandarias'),
  ('Hohenau'),
  ('Horqueta'),
  ('Humaitá'),
  ('Independencia'),
  ('Iruña'),
  ('Isla Pucú'),
  ('Isla Umbú'),
  ('Itá'),
  ('Itacurubí de la Cordillera'),
  ('Itacurubí del Rosario'),
  ('Itakyry'),
  ('Itanará'),
  ('Itapé'),
  ('Itapúa Poty'),
  ('Itauguá'),
  ('Iturbe'),
  ('J. Augusto Saldívar'),
  ('Jesús'),
  ('José Domingo Ocampos'),
  ('José Falcón'),
  ('José Fassardi'),
  ('José Leandro Oviedo'),
  ('Juan de Mena'),
  ('Juan E. O''Leary'),
  ('Karapaí'),
  ('Katueté'),
  ('La Catedral'),
  ('La Colmena'),
  ('La Encarnación'),
  ('La Paloma del Espíritu Santo'),
  ('La Pastora'),
  ('La Paz'),
  ('La Recoleta'),
  ('Lambaré'),
  ('Laurel'),
  ('Laureles'),
  ('Liberación'),
  ('Lima'),
  ('Limpio'),
  ('Loma Grande'),
  ('Loma Plata'),
  ('Loreto'),
  ('Los Cedrales'),
  ('Luque'),
  ('Maciel'),
  ('Maracaná'),
  ('María Antonia'),
  ('Mariano Roque Alonso'),
  ('Mariscal Francisco Solano López'),
  ('Mariscal José Félix Estigarribia'),
  ('Mayor Martinez'),
  ('Mayor Otaño'),
  ('Mbaracayú'),
  ('Mbocayaty'),
  ('Mbocayaty del Yhaguy'),
  ('Mbuyapey'),
  ('Minga Guazú'),
  ('Minga Porá'),
  ('Nanawa'),
  ('Naranjal'),
  ('Natalicio Talavera'),
  ('Natalio'),
  ('Nueva Alborada'),
  ('Nueva Asunción'),
  ('Nueva Colombia'),
  ('Nueva Esperanza'),
  ('Nueva Germania'),
  ('Nueva Italia'),
  ('Nueva Londres'),
  ('Nueva Toledo'),
  ('Ñacunday'),
  ('Ñemby'),
  ('Ñumí'),
  ('Obligado'),
  ('Paraguarí'),
  ('Paso Barreto'),
  ('Paso de Patria'),
  ('Paso Horqueta'),
  ('Paso Yobai'),
  ('Pedro Juan Caballero'),
  ('Pilar'),
  ('Pirapó'),
  ('Pirayú'),
  ('Piribebuy'),
  ('Presidente Franco'),
  ('Primero de Marzo'),
  ('Puerto Adela'),
  ('Puerto Casado'),
  ('Puerto Pinasco'),
  ('Quiindy'),
  ('Quyquyhó'),
  ('R.I.3 Corrales'),
  ('Raúl Arsenio Oviedo'),
  ('Repatriación'),
  ('Salto del Guairá'),
  ('San Alberto'),
  ('San Alfredo'),
  ('San Antonio'),
  ('San Bernardino'),
  ('San Carlos'),
  ('San Cosme y Damian'),
  ('San Cristobal'),
  ('San Estanislao'),
  ('San Ignacio'),
  ('San Joaquín'),
  ('San José de los Arroyos'),
  ('San José del Rosario'),
  ('San José Obrero'),
  ('San Juan Bautista de las Misiones'),
  ('San Juan Bautista de Ñeembucú'),
  ('San Juan del Paraná'),
  ('San Juan Nepomuceno'),
  ('San Lázaro'),
  ('San Lorenzo'),
  ('San Miguel'),
  ('San Pablo'),
  ('San Patricio'),
  ('San Pedro del Paraná'),
  ('San Pedro del Ycuamandyyú'),
  ('San Rafael del Paraná'),
  ('San Roque'),
  ('San Roque Gonzalez'),
  ('San Salvador'),
  ('San Vicente Pancholo'),
  ('Santa Elena'),
  ('Santa Fe del Paraná'),
  ('Santa María'),
  ('Santa Maria de Asunción'),
  ('Santa Rita'),
  ('Santa Rosa'),
  ('Santa Rosa del Aguaray'),
  ('Santa Rosa del Mbutuy'),
  ('Santa Rosa del Monday'),
  ('Santiago'),
  ('Santísima Trinidad'),
  ('Sapucái'),
  ('Sargento José Félix López'),
  ('Simón Bolivar'),
  ('Tacuaras'),
  ('Tacuatí'),
  ('Tavaí'),
  ('Tavapy'),
  ('Tebicuary'),
  ('Tebicuary-Mí'),
  ('Tembiaporá'),
  ('Teniente 1° Manuel Irala Fernández'),
  ('Teniente Esteban Martínez'),
  ('Tobatí'),
  ('Tomás Romero Pereira'),
  ('Trinidad'),
  ('Unión'),
  ('Valenzuela'),
  ('Vaquería'),
  ('Villa del Rosario'),
  ('Villa Elisa'),
  ('Villa Florida'),
  ('Villa Franca'),
  ('Villa Hayes'),
  ('Villa Oliva'),
  ('Villa Ygatimí'),
  ('Villalbín'),
  ('Villarrica'),
  ('Villeta'),
  ('Yabebyry'),
  ('Yaguarón'),
  ('Yasy Cañy'),
  ('Yataity'),
  ('Yataity del Norte'),
  ('Yatytay'),
  ('Yby Pytá'),
  ('Yby Yaú'),
  ('Ybycuí'),
  ('Ybyrarobaná'),
  ('Ybytymí'),
  ('Yegros'),
  ('Yguazú'),
  ('Yhú'),
  ('Ypacaraí'),
  ('Ypané'),
  ('Ypejhú'),
  ('Yrybucua'),
  ('Yuty'),
  ('Zanja Pyta')
  ON CONFLICT (nombre) DO NOTHING;
END $migration$;

COMMIT;
